sudo: required
services:
  - docker


before_install:
  - docker build -t mbenkhal27/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mbenkhal27/react-test npm test  -- --coverage 


after_success:
  - docker build -t mbenkhal27/multi-client  ./client 
  - docker build -t mbenkhal27/multi-nginx ./nginx
  - docker build -t mbenkhal27/multi-server ./server
  - docker build -t mbenkhal27/multi-worker ./worker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
 --password-stdin  
  - docker push  mbenkhal27/multi-client 
  - docker push  mbenkhal27/multi-nginx 
  - docker push  mbenkhal27/multi-server 
  - docker push  mbenkhal27/multi-worker 


  